// src/demo.ts
// ─────────────────────────────────────────────────────────────────────────────
// CLI demo runner — outputs the post-mortem draft to the terminal.
//
// Run with:
//   npm run demo:mock    → offline, no credentials needed
//   npm run demo:real    → live Slack/GitHub/OpsGenie APIs (keys required in .env)
//
// For a browser-based demo (CodeSandbox), see src/server.ts instead.
// ─────────────────────────────────────────────────────────────────────────────

import "dotenv/config";
import * as readline from "readline/promises";
import { stdin as input, stdout as output } from "process";
import { describeContextWithoutLlm } from "./generate";
import { resolveRuntimeMode, runPostmortemFlow } from "./workflow";

async function main(): Promise<void> {
  const mode = resolveRuntimeMode(process.env.MODE);

  console.log(`\n=== Postmortem Bot — ${mode.toUpperCase()} MODE ===\n`);

  // In real mode, ask the engineer which channel to read
  let channelInput: string | undefined;
  if (mode === "real") {
    const rl = readline.createInterface({ input, output });
    channelInput = await rl.question("Enter Slack channel ID or #channel-name: ");
    rl.close();
  }

  // Run the full pipeline (context assembly → gap detection → draft generation)
  const result = await runPostmortemFlow({ mode, channelInput });

  // Print the result
  console.log("─".repeat(60));
  console.log(
    result.usedFallback
      ? "⚠  Fallback draft (no ANTHROPIC_API_KEY set)"
      : "✓  Draft generated by postmortem-bot"
  );
  console.log("   Engineer review required before publishing.");
  console.log("─".repeat(60));
  console.log("");

  if (result.gaps.length) {
    console.log("Data gaps noted in draft:");
    result.gaps.forEach((g) => console.log(`  • ${g}`));
    console.log("");
  }

  console.log(result.draft);

  // If no API key, show what data would have been sent to Claude
  if (result.usedFallback) {
    console.log("\n" + "─".repeat(60));
    console.log(describeContextWithoutLlm(result.context));
  }
}

main().catch((err) => {
  console.error("\nError:", err instanceof Error ? err.message : err);
  process.exit(1);
});