import "dotenv/config";
import * as readline from "readline/promises";
import { stdin as input, stdout as output } from "process";
import { describeContextWithoutLlm } from "./generate";
import { resolveRuntimeMode, runPostmortemFlow } from "./workflow";

async function main(): Promise<void> {
  const mode = resolveRuntimeMode(process.env.MODE);
  let channelInput: string | undefined;
  if (mode === "real") {
    const rl = readline.createInterface({ input, output });
    channelInput = await rl.question("Enter Slack channel ID or #channel-name: ");
    rl.close();
  }

  const result = await runPostmortemFlow({ mode, channelInput });
  console.log(
    result.usedFallback
      ? "_Draft generated by postmortem-bot (fallback mode, no ANTHROPIC_API_KEY)._"
      : "_Draft generated by postmortem-bot. Engineer review required before publishing._"
  );
  console.log("");
  if (result.gaps.length) {
    console.log("_Source gaps (review in draft):_", result.gaps.join(" "), "\n");
  }
  console.log(result.draft);

  if (result.usedFallback) {
    console.log("\n---\n");
    console.log(describeContextWithoutLlm(result.context));
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
