import "dotenv/config";
import { App } from "@slack/bolt";
import { describeContextWithoutLlm } from "./generate";
import { resolveRuntimeMode, runPostmortemFlow } from "./workflow";

const mode = resolveRuntimeMode(process.env.MODE);
const signingSecret = process.env.SLACK_SIGNING_SECRET;
const token = process.env.SLACK_BOT_TOKEN;

if (mode === "real" && (!signingSecret || !token)) {
  console.error("Missing SLACK_SIGNING_SECRET or SLACK_BOT_TOKEN");
  process.exit(1);
}

const app = new App({
  signingSecret: signingSecret ?? "mock-signing-secret",
  token: token ?? "mock-bot-token",
  port: Number(process.env.PORT ?? 3000),
});

app.command("/postmortem", async ({ command, ack, client, respond }) => {
  await ack();
  const raw = command.text?.trim() ?? "";
  if (!raw) {
    await respond({
      response_type: "ephemeral",
      text: "Usage: `/postmortem #incident-channel` or `/postmortem C0123456789`",
    });
    return;
  }

  try {
    const result = await runPostmortemFlow({
      mode,
      channelInput: mode === "real" ? raw : undefined,
    });
    let body =
      "*Draft generated by postmortem-bot. Engineer review required before publishing.*\n\n" +
      result.draft;
    if (result.gaps.length) {
      body += `\n\n_Source gaps:_ ${result.gaps.join(" ")}`;
    }
    if (result.usedFallback) {
      body +=
        "\n\n---\npostmortem-bot note: ANTHROPIC_API_KEY is not set, so this draft is generated from fallback logic.\n\n```\n" +
        describeContextWithoutLlm(result.context) +
        "\n```";
    }

    await client.chat.postMessage({
      channel: result.context.channelId,
      text: body,
      mrkdwn: true,
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    await respond({
      response_type: "ephemeral",
      text: `postmortem-bot error: ${msg}`,
    });
  }
});

(async () => {
  if (mode === "mock") {
    console.log(
      "MODE=mock set. Slack server start skipped. Run `npm run demo:mock` for the offline workflow."
    );
    return;
  }
  await app.start();
  console.log(`postmortem-bot listening on port ${process.env.PORT ?? 3000}`);
})();
