// src/index.ts
// ─────────────────────────────────────────────────────────────────────────────
// Production Slack bot — handles the /postmortem slash command.
//
// ⚠ IN PROGRESS — this file is complete and correct, but it cannot be tested
// without a registered Slack app, a public HTTPS webhook URL, and valid
// SLACK_BOT_TOKEN + SLACK_SIGNING_SECRET credentials.
//
// For a working demo, use:
//   npm start         → web demo (no credentials)
//   npm run demo:mock → terminal demo (no credentials)
//
// To run in production:
//   1. Create a Slack app at api.slack.com/apps
//   2. Add a slash command /postmortem pointing to your server URL + /slack/events
//   3. Grant OAuth scopes: channels:history, channels:read, chat:write, commands
//   4. Fill in .env (SLACK_BOT_TOKEN, SLACK_SIGNING_SECRET, ANTHROPIC_API_KEY)
//   5. Run: MODE=real npm run start:prod
//   6. Expose your server publicly (ngrok http 3000 for local development)
// ─────────────────────────────────────────────────────────────────────────────

import "dotenv/config";
import { App } from "@slack/bolt";
import { describeContextWithoutLlm } from "./generate";
import { resolveRuntimeMode, runPostmortemFlow } from "./workflow";

const mode = resolveRuntimeMode(process.env.MODE);

// Guard: in real mode, both Slack credentials must be present
const signingSecret = process.env.SLACK_SIGNING_SECRET;
const token = process.env.SLACK_BOT_TOKEN;

if (mode === "real" && (!signingSecret || !token)) {
  console.error("Error: SLACK_SIGNING_SECRET and SLACK_BOT_TOKEN are both required in real mode.");
  console.error("See .env.example for setup instructions.");
  process.exit(1);
}

// Initialise the Slack Bolt app
const app = new App({
  signingSecret: signingSecret ?? "mock-signing-secret",
  token: token ?? "mock-bot-token",
  port: Number(process.env.PORT ?? 3000),
});

// ── /postmortem slash command handler ─────────────────────────────────────────
//
// Flow:
//   1. Acknowledge the command immediately (Slack requires this within 3 seconds)
//   2. Tell the engineer we're working on it (ephemeral — only they see it)
//   3. Run the full post-mortem pipeline with the incident channel they provided
//   4. Post the draft to the incident channel (visible to everyone)
//   5. If anything fails, send an ephemeral error message to the engineer

app.command("/postmortem", async ({ command, ack, client, respond }) => {

  // Step 1: acknowledge immediately — Slack times out after 3 seconds
  await ack();

  const channelInput = command.text?.trim() ?? "";
  if (!channelInput) {
    await respond({
      response_type: "ephemeral",
      text: "Usage: `/postmortem #incident-channel-name` or `/postmortem C0123456789`",
    });
    return;
  }

  // Step 2: let the engineer know we're working on it
  await respond({
    response_type: "ephemeral",
    text: `Fetching incident context from ${channelInput}... this takes about 10 seconds.`,
  });

  try {
    // Step 3: run the full pipeline
    const result = await runPostmortemFlow({
      mode,
      channelInput: mode === "real" ? channelInput : undefined,
    });

    // Build the message body
    let body =
      "*Post-mortem draft — generated by postmortem-bot*\n" +
      "_Engineer review required before publishing._\n\n" +
      result.draft;

    if (result.gaps.length) {
      body += `\n\n_Data gaps:_ ${result.gaps.join(" ")}`;
    }

    // If running without an Anthropic key, show the context that would have been sent
    if (result.usedFallback) {
      body +=
        "\n\n---\n_Note: ANTHROPIC_API_KEY is not set — draft generated by fallback logic._\n\n```\n" +
        describeContextWithoutLlm(result.context) +
        "\n```";
    }

    // Step 4: post the draft to the incident channel
    await client.chat.postMessage({
      channel: result.context.channelId,
      text: body,
      mrkdwn: true,
    });

  } catch (e) {
    // Step 5: send an ephemeral error if anything went wrong
    const msg = e instanceof Error ? e.message : String(e);
    await respond({
      response_type: "ephemeral",
      text: `postmortem-bot error: ${msg}`,
    });
  }
});

// ── Start ─────────────────────────────────────────────────────────────────────

(async () => {
  if (mode === "mock") {
    // In mock mode, there's nothing to start — the Slack server needs real credentials.
    // Use `npm start` for the web demo or `npm run demo:mock` for the terminal demo.
    console.log("MODE=mock: Slack server not started.");
    console.log("Run `npm start` for the web demo or `npm run demo:mock` for the terminal demo.");
    return;
  }

  await app.start();
  console.log(`postmortem-bot Slack server running on port ${process.env.PORT ?? 3000}`);
  console.log("Listening for /postmortem slash commands...");
})();