// src/server.ts
// ─────────────────────────────────────────────────────────────────────────────
// Web server demo — renders the post-mortem draft as an HTML page.
//
// This is the DEFAULT entry point (npm start) and what CodeSandbox runs.
// It always runs in mock mode (no credentials needed) and serves the
// generated draft at http://localhost:3000.
//
// Open the browser preview in CodeSandbox to see the rendered output.
//
// Uses only Node.js built-in modules (no Express needed).
// ─────────────────────────────────────────────────────────────────────────────

import "dotenv/config";
import * as http from "http";
import { describeContextWithoutLlm } from "./generate";
import { runPostmortemFlow } from "./workflow";

const PORT = Number(process.env.PORT ?? 3000);

// ── Markdown → HTML converter ─────────────────────────────────────────────────
// Converts the 7-section markdown draft into readable HTML.
// Handles: ## headings, bullet lists, inline code, bold, line breaks.

function markdownToHtml(md: string): string {
  const lines = md.split("\n");
  const html: string[] = [];
  let inList = false;

  for (const raw of lines) {
    const line = raw.trimEnd();

    if (line.startsWith("## ")) {
      if (inList) { html.push("</ul>"); inList = false; }
      html.push(`<h2>${escHtml(line.slice(3))}</h2>`);

    } else if (line.startsWith("### ")) {
      if (inList) { html.push("</ul>"); inList = false; }
      html.push(`<h3>${escHtml(line.slice(4))}</h3>`);

    } else if (line.startsWith("- ") || line.startsWith("• ")) {
      if (!inList) { html.push("<ul>"); inList = true; }
      html.push(`<li>${inlineFormat(line.slice(2))}</li>`);

    } else if (line === "") {
      if (inList) { html.push("</ul>"); inList = false; }
      html.push("<br>");

    } else {
      if (inList) { html.push("</ul>"); inList = false; }
      html.push(`<p>${inlineFormat(line)}</p>`);
    }
  }
  if (inList) html.push("</ul>");
  return html.join("\n");
}

function escHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function inlineFormat(s: string): string {
  return escHtml(s)
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/(https?:\/\/[^\s<]+)/g, '<a href="$1" target="_blank">$1</a>');
}

// ── HTML page template ────────────────────────────────────────────────────────

function buildHtmlPage(params: {
  channelName: string;
  draft: string;
  gaps: string[];
  usedFallback: boolean;
  contextJson?: string;
}): string {
  const { channelName, draft, gaps, usedFallback, contextJson } = params;

  const gapHtml = gaps.length
    ? `<div class="gaps"><strong>Data gaps:</strong><ul>${gaps.map((g) => `<li>${escHtml(g)}</li>`).join("")}</ul></div>`
    : "";

  const fallbackNote = usedFallback
    ? `<div class="notice warning">
        ⚠ This draft was generated by the built-in fallback (no <code>ANTHROPIC_API_KEY</code> set).
        Set your key in <code>.env</code> to get a Claude-powered draft instead.
       </div>`
    : `<div class="notice success">✓ Draft generated by postmortem-bot · Engineer review required before publishing.</div>`;

  const contextSection = contextJson
    ? `<details>
        <summary>Context sent to the LLM (click to expand)</summary>
        <pre class="context-json">${escHtml(contextJson)}</pre>
       </details>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Post-mortem — #${escHtml(channelName)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      font-size: 15px;
      line-height: 1.6;
      color: #1a1a2e;
      background: #f4f6fb;
      padding: 2rem 1rem;
    }
    .page { max-width: 820px; margin: 0 auto; }
    header {
      background: #1a1a2e;
      color: #fff;
      padding: 1.5rem 2rem;
      border-radius: 10px 10px 0 0;
    }
    header h1 { font-size: 1.3rem; font-weight: 600; }
    header .sub { font-size: 0.85rem; opacity: 0.6; margin-top: 0.2rem; }
    .card {
      background: #fff;
      padding: 2rem;
      border-radius: 0 0 10px 10px;
      box-shadow: 0 2px 12px rgba(0,0,0,0.07);
    }
    .notice {
      padding: 0.75rem 1rem;
      border-radius: 6px;
      margin-bottom: 1.5rem;
      font-size: 0.88rem;
    }
    .notice.success { background: #e6f9f0; color: #166534; border-left: 4px solid #22c55e; }
    .notice.warning { background: #fef9ec; color: #854d0e; border-left: 4px solid #f59e0b; }
    .gaps {
      background: #f0f4ff;
      border-left: 4px solid #6366f1;
      padding: 0.75rem 1rem;
      border-radius: 6px;
      margin-bottom: 1.5rem;
      font-size: 0.88rem;
    }
    .gaps ul { margin: 0.4rem 0 0 1.2rem; }
    h2 {
      font-size: 1.05rem;
      font-weight: 700;
      color: #1a1a2e;
      border-bottom: 2px solid #e8eaf0;
      padding-bottom: 0.4rem;
      margin: 1.8rem 0 0.8rem;
    }
    h2:first-child { margin-top: 0; }
    h3 { font-size: 0.95rem; font-weight: 600; margin: 1rem 0 0.4rem; }
    p { margin: 0.4rem 0; }
    ul { margin: 0.4rem 0 0.4rem 1.4rem; }
    li { margin: 0.2rem 0; }
    code {
      background: #f1f3f8;
      padding: 0.1em 0.35em;
      border-radius: 4px;
      font-size: 0.88em;
      font-family: "SF Mono", Menlo, Consolas, monospace;
    }
    a { color: #6366f1; }
    strong { font-weight: 600; }
    br { display: block; content: ""; margin: 0.3rem 0; }
    details { margin-top: 2rem; border-top: 1px solid #e8eaf0; padding-top: 1rem; }
    summary {
      cursor: pointer;
      font-size: 0.88rem;
      color: #6366f1;
      user-select: none;
    }
    pre.context-json {
      background: #f8f9fc;
      border: 1px solid #e8eaf0;
      border-radius: 6px;
      padding: 1rem;
      overflow-x: auto;
      font-size: 0.78rem;
      margin-top: 0.8rem;
      white-space: pre-wrap;
      word-break: break-word;
    }
    .draft { margin-top: 0.5rem; }
  </style>
</head>
<body>
  <div class="page">
    <header>
      <div class="h1">postmortem-bot</div>
      <div class="sub">Channel: #${escHtml(channelName)} · Mock incident data · Auto-generated draft</div>
    </header>
    <div class="card">
      ${fallbackNote}
      ${gapHtml}
      <div class="draft">${markdownToHtml(draft)}</div>
      ${contextSection}
    </div>
  </div>
</body>
</html>`;
}

// ── HTTP server ───────────────────────────────────────────────────────────────

const server = http.createServer(async (_req, res) => {
  try {
    // Always run in mock mode — no credentials needed
    const result = await runPostmortemFlow({ mode: "mock" });

    const contextJson = result.usedFallback
      ? describeContextWithoutLlm(result.context)
      : undefined;

    const html = buildHtmlPage({
      channelName: result.context.channelName ?? result.context.channelId,
      draft: result.draft,
      gaps: result.gaps,
      usedFallback: result.usedFallback,
      contextJson,
    });

    res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
    res.end(html);

  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    res.writeHead(500, { "Content-Type": "text/plain; charset=utf-8" });
    res.end(`Error generating post-mortem:\n\n${msg}`);
  }
});

server.listen(PORT, () => {
  console.log(`postmortem-bot web demo running at http://localhost:${PORT}`);
  console.log("Open the browser preview to see the rendered post-mortem draft.");
  console.log("Running in mock mode — no credentials needed.");
});